name: perostab
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy>=1.26
  - pandas>=2.0
  - scikit-learn>=1.3
  - matplotlib>=3.7
  - shap>=0.42
  - typer>=0.9
  - joblib>=1.3
  - statsmodels>=0.14
  - imbalanced-learn>=0.11
  - pip
  - pip:
      - pre-commit>=3.3
      - black>=23.7
      - isort>=5.12
      - flake8>=6.1
      - mypy>=1.5
      - pytest>=7.4
      - jupyter>=1.0
